language: node_js
node_js:
  - node
  - 7
  - 6
services:
  - mongodb
  - redis-server
env:
  - MONGODB=mongodb://localhost:27017/pillo
  - REDIS_URL=redis://localhost:6379
before_script:
  - npm run build
  - sleep 15
